# Generated by Django 2.2.6 on 2020-11-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='counrtry',
            table='country',
        ),
    ]
