# Generated by Django 2.2.6 on 2020-11-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20201119_1633'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counrtry',
            new_name='Country',
        ),
    ]
