# Generated by Django 2.2.8 on 2021-01-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20210114_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite_restaurant',
            old_name='added_time',
            new_name='time',
        ),
    ]
