# Generated by Django 2.2.6 on 2019-12-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchrecord',
            name='user_id',
        ),
        migrations.AddField(
            model_name='searchrecord',
            name='username',
            field=models.TextField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
