# Generated by Django 2.2.6 on 2019-12-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_record', '0002_auto_20191229_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrecord',
            name='range',
            field=models.IntegerField(),
        ),
    ]
