# Generated by Django 3.0 on 2019-12-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.TextField(blank=True, db_column='jobName', null=True)),
                ('jobaddress', models.TextField(blank=True, db_column='jobAddress', null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConvenienceStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenience_class', models.TextField(blank=True, null=True)),
                ('convenience_name', models.TextField(blank=True, null=True)),
                ('convenience_address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'convenience_store',
                'managed': True,
            },
        ),
    ]
