# Generated by Django 2.2.6 on 2019-12-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBMgr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('location', models.TextField()),
                ('locationName', models.TextField()),
            ],
            options={
                'db_table': 'show',
                'managed': True,
            },
        ),
    ]
