# Generated by Django 3.0 on 2019-12-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBMgr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('title', models.TextField()),
                ('location', models.TextField()),
                ('locationName', models.TextField()),
                ('latitude', models.TextField(default='0.0')),
                ('longitude', models.TextField(default='0.0')),
            ],
            options={
                'db_table': 'show',
            },
        ),
    ]
