# Generated by Django 3.0 on 2019-12-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBMgr', '0002_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='uid',
        ),
    ]
