# Generated by Django 2.2.6 on 2019-12-16 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBMgr', '0003_remove_show_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'managed': True},
        ),
    ]
