# Generated by Django 2.2.6 on 2019-12-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBMgr', '0004_auto_20191216_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='joblatitude',
            field=models.TextField(default='0.0'),
        ),
        migrations.AddField(
            model_name='company',
            name='joblongitude',
            field=models.TextField(default='0.0'),
        ),
        migrations.AddField(
            model_name='conveniencestore',
            name='convenience_latitude',
            field=models.TextField(default='0.0'),
        ),
        migrations.AddField(
            model_name='conveniencestore',
            name='convenience_longitude',
            field=models.TextField(default='0.0'),
        ),
    ]
