# Generated by Django 2.2.6 on 2019-12-29 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBMgr', '0005_auto_20191220_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conveniencestore',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='favoriteshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_title', models.CharField(max_length=100)),
                ('favorite_address', models.CharField(max_length=1000)),
                ('favorite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBMgr.show')),
            ],
        ),
    ]
