# Generated by Django 2.2.6 on 2019-12-29 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DBMgr', '0006_auto_20191229_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteshow',
            name='favorite_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
