# Generated by Django 2.2.6 on 2019-12-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBMgr', '0007_favoriteshow_favorite_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteshow',
            name='favorite_id',
        ),
        migrations.AddField(
            model_name='favoriteshow',
            name='favorite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DBMgr.show'),
        ),
    ]
