# Generated by Django 2.2.6 on 2019-12-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBMgr', '0008_auto_20191229_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteshow',
            name='favorite_address',
        ),
        migrations.RemoveField(
            model_name='favoriteshow',
            name='favorite_title',
        ),
    ]
