# Generated by Django 2.2.6 on 2019-12-29 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBMgr', '0010_favoritecompany_favoritestore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecompany',
            name='favorite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DBMgr.Company'),
        ),
        migrations.AlterField(
            model_name='favoritestore',
            name='favorite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DBMgr.ConvenienceStore'),
        ),
    ]
