# Generated by Django 2.2.6 on 2019-12-29 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DBMgr', '0011_auto_20191230_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecompany',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='favoriteshow',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='favoritestore',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
