# Generated by Django 2.2.6 on 2019-12-30 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBMgr', '0012_auto_20191230_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteshow',
            name='favorite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='show_related', to='DBMgr.show'),
        ),
    ]
