# Generated by Django 2.2.6 on 2020-12-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.TextField()),
                ('restaurant_address', models.TextField()),
                ('city_id', models.ForeignKey(default=1, on_delete='models.CASCADE', to='areas.City')),
                ('country_id', models.ForeignKey(default=1, on_delete='models.CASCADE', to='areas.Country')),
            ],
            options={
                'db_table': 'restaurant',
                'managed': True,
            },
        ),
    ]
