# Generated by Django 2.2.6 on 2020-11-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.TextField()),
                ('restaurant_address', models.TextField()),
            ],
            options={
                'db_table': 'restaurant',
                'managed': True,
            },
        ),

    ]
